// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA3u1_di6b_jxKN83Ct6mm2e21MIM5zJcA',
    appId: '1:570606155967:web:e787a97d31a8dc91082e0a',
    messagingSenderId: '570606155967',
    projectId: 'campuscruise-c63a4',
    authDomain: 'campuscruise-c63a4.firebaseapp.com',
    storageBucket: 'campuscruise-c63a4.appspot.com',
    measurementId: 'G-KCFF7ZKV4M',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD92VdvWE6Dqi3l42lxy0SgcCKb5h0UYjY',
    appId: '1:570606155967:android:208e5e2462207be6082e0a',
    messagingSenderId: '570606155967',
    projectId: 'campuscruise-c63a4',
    storageBucket: 'campuscruise-c63a4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDzzU571eRRenNC8MlywhXbIJ5cqYPQSVo',
    appId: '1:570606155967:ios:2eca57de4b882fcf082e0a',
    messagingSenderId: '570606155967',
    projectId: 'campuscruise-c63a4',
    storageBucket: 'campuscruise-c63a4.appspot.com',
    iosBundleId: 'com.example.campusRide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDzzU571eRRenNC8MlywhXbIJ5cqYPQSVo',
    appId: '1:570606155967:ios:7063a1c2009f6b69082e0a',
    messagingSenderId: '570606155967',
    projectId: 'campuscruise-c63a4',
    storageBucket: 'campuscruise-c63a4.appspot.com',
    iosBundleId: 'com.example.campusRide.RunnerTests',
  );
}
